# Generated by Django 2.2.4 on 2019-08-17 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Guias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('frase', models.CharField(max_length=255)),
                ('foto', models.CharField(max_length=255)),
                ('facebook', models.CharField(max_length=255)),
                ('instagram', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=255)),
                ('id_categorias', models.ManyToManyField(to='guiaTurismo.Categorias')),
                ('id_ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guiaTurismo.Ciudades')),
            ],
        ),
        migrations.CreateModel(
            name='Tours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('precio', models.FloatField(max_length=255)),
                ('url_imagen_mapa', models.CharField(max_length=500)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guiaTurismo.Categorias')),
                ('id_guia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guiaTurismo.Guias')),
            ],
        ),
    ]
