# Generated by Django 2.2.4 on 2019-08-18 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guiaTurismo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phrase', models.CharField(max_length=255)),
                ('photo', models.CharField(max_length=255)),
                ('facebook', models.CharField(max_length=255)),
                ('instagram', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField(max_length=255)),
                ('url_map_image', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='tours',
            name='id_categoria',
        ),
        migrations.RemoveField(
            model_name='tours',
            name='id_guia',
        ),
        migrations.DeleteModel(
            name='Guias',
        ),
        migrations.DeleteModel(
            name='Tours',
        ),
        migrations.DeleteModel(
            name='Categorias',
        ),
        migrations.DeleteModel(
            name='Ciudades',
        ),
        migrations.AddField(
            model_name='tour',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guiaTurismo.Category'),
        ),
        migrations.AddField(
            model_name='tour',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guiaTurismo.Guide'),
        ),
        migrations.AddField(
            model_name='guide',
            name='category',
            field=models.ManyToManyField(to='guiaTurismo.Category'),
        ),
        migrations.AddField(
            model_name='guide',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guiaTurismo.City'),
        ),

    ]
