# Generated by Django 2.2.4 on 2019-08-24 23:39

from django.db import migrations, models
import guiaTurismo.models


class Migration(migrations.Migration):

    dependencies = [
        ('guiaTurismo', '0002_auto_20190818_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='photo',
            field=models.ImageField(default='', max_length=255, upload_to=guiaTurismo.models.user_directory_filepath),
        ),
    ]
